### ISSUE TITLE
warning日志不输出

### ISSUE THREAD

**Issue by chenhebing** [keenwon/elint#3]
#### 环境信息

- 系统: Macos
- Node.js 版本: 8.11.2
- npm 版本: 6.4.1

#### 问题描述

我们配置了eslintignore，运行elint lint 的时候输出了全是 --no-ignore的warning，导致error根本看不到（terminal显示日志有限）

能否提供option不输出warning，或者error在下，warning在上的输出，谢谢

**Comment by keenwon** [comment]
已经调整为 warnings 在前，errors 在后
升级 elint ^1.8.0 试试
有问题提 Issue

**Comment by chenhebing** [comment]
> 已经调整为 warnings 在前，errors 在后
> 升级 elint ^1.8.0 试试
> 有问题提 Issue

好的 thx
